INSERT INTO USER (USER_NAME, IS_SELLER) VALUES ('Ozzy', true);
INSERT INTO USER (USER_NAME, IS_SELLER) VALUES ('Max', false);
INSERT INTO USER (USER_NAME, IS_SELLER) VALUES ('Jorel', false);
INSERT INTO USER (USER_NAME, IS_SELLER) VALUES ('Lara', false);
INSERT INTO SELLER (ID_USER, FOLLOWERS_COUNT) VALUES (1, 0);